minimal_mistakes_skin    : "default" # "air", "contrast", "dark", "dirt", "mint", "sunrise"

# Site Settings
locale                   : "ja_JP"
title                    : "u6k.Blog"
title_separator          : "-"
name                     : "u6k"
description              : "プログラミングやWebサービスと戯れたログを残しています。"
url                      : # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
# breadcrumbs            : false # true, false (default)

# Social Sharing
twitter:
  username               : "u6k_yu1"
facebook:
  username               : "yuuichi.naono"

# Site Author
author:
  name             : "u6k"
  avatar           : "http://gravatar.com/avatar/7cbe65037b17a6ee6711ce18b1e97638"
  bio              : "プログラミングやWebサービスと戯れたログを残しています。"
  location         : "Japan"
  email            : "u6k.apps@gmail.com"
  facebook         : "yuuichi.naono"
  github           : "u6k"
  twitter          : "u6k_yu1"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
#permalink: /:categories/:title/
paginate: 10
paginate_path: /page:num/
timezone: Asia/Tokyo # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
future: true

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-plantuml
  - jekyll-redirect-from

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      share: true
      related: false
      toc: true
      toc_label: "目次"
      toc_sticky: true

# Analytics
analytics:
  provider: google
  google:
    tracking_id: UA-112068302-1
