version: '3'

services:
  blog:
    build: .
    volumes:
      - "./:/var/my-blog/"
  http:
    image: nginx
    volumes:
      - "./_site/:/usr/share/nginx/html"
    ports:
      - "8080:80"
