version: 2
jobs:
    build:
        working_directory: ~/repo
        docker:
            - image: docker:17.07.0-ce-git
        steps:
            - checkout
            - setup_remote_docker
            - run:
                name: Build docker image
                command: |
                    docker build -t u6kapps/blog .
            - run:
                name: Push docker image
                command: |
                    if [ "${CIRCLE_BRANCH}" == "master" ]; then
                        docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
                        docker tag u6kapps/blog u6kapps/blog:${CIRCLE_SHA1}
                        docker push u6kapps/blog
                    else
                        echo skip deploy
                    fi