locale: ja
title: u6k.log()
title_separator: "|"
name: u6k
email: u6k.apps@gmail.com
description: プログラミングやWebサービスと戯れたログを残しています。

# Social Sharing
twitter:
  username: u6k_yu1

# Site Author
author:
  name: u6k
  avatar:
  email: u6k.apps@gmail.com

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
exclude:
  - Gemfile
  - Gemfile.lock

highlighter: rouge

paginate: 10
paginate_path: /page_:num/
timezone: Asia/Tokyo

tag_archive:
  type: liquid
  path: /tags/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
